import numpy as np
#insert element in array 
#syntax: np.insert(arr, index, values , axis=None)
#axis=0 for row, axis=1 for column
arr=np.array([1, 2, 3,4,5,6])
new_arr=np.insert(arr, 3, 10, axis=0)
print("Array after inserting element:")
print(new_arr)
print(arr)
print()
arr_2d=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
#inserting a new row
new_arr_2d=np.insert(arr_2d, 1, [10, 11, 12], axis=None)
new_arr_2d1=np.insert(arr_2d, 1, [10, 11, 12], axis=0)
new_arr_2d2=np.insert(arr_2d, 1, [10, 11, 12], axis=1)
print("2D Array after inserting a new row:")
print(new_arr_2d)
print()
print("2D Array after inserting a new row:")
print(new_arr_2d1)
print()
print("2D Array after inserting a new column:")
print(new_arr_2d2)
print()

#appenrd element to array
#syntax: np.append(arr, values, axis=None)
#axis=0 for row, axis=1 for column
arr2=np.array([1,2,3,4,5,6])
appended_arr=np.append(arr2,10)
print("Array after appending element:")
print(appended_arr)
print(arr2)
print()
#concatenate two arrays
#syntax: np.concatenate((arr1, arr2), axis=0)
arr3=np.array([1,2,3])
arr4=np.array([4,5,6])
concatenated_arr=np.concatenate((arr3, arr4), axis=0)
print("Concatenated array:")
print(concatenated_arr)
print()
#remove element from array
#syntax: np.delete(arr, index, axis=None)
arr5=np.array([1,2,3,4,5,6])
deleted_arr=np.delete(arr5, 2, axis=0)
print("Array after deleting element:")
print(deleted_arr)
print(arr5)
arr_2d2=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
deleted_arr_2d=np.delete(arr_2d2, 1, axis=0)
print("2D Array after deleting a row:")
print(deleted_arr_2d)
print()
#stacking arrays
#syntax: np.stack((arr1, arr2), axis=0)
#vertical stacking
#syntax: np.vstack((arr1, arr2))
#horizontal stacking
#syntax: np.hstack((arr1, arr2))
arr6=np.array([1,2,3])
arr7=np.array([4,5,6])
stacked_arr=np.stack((arr6, arr7), axis=0)
print("Stacked array:")
print(stacked_arr)
print()
vstacked_arr=np.vstack((arr6, arr7))
print("Vertically stacked array:")
print(vstacked_arr)
print()
hstacked_arr=np.hstack((arr6, arr7))
print("Horizontally stacked array:")
print(hstacked_arr)
print()
#splitting arrays
#syntax: np.split(arr, indices_or_sections, axis=0)
#horizontal splitting
#syntax: np.hsplit(arr, indices_or_sections)
#vertical splitting
#syntax: np.vsplit(arr, indices_or_sections)
arr8=np.array([1,2,3,4,5,6])
split_arr=np.split(arr8, 2)
print("Split array:")
print(split_arr)
print()
